import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3000;

app.use(express.json());

// API route for Gemini summarization
app.post("/api/gemini/summarize", async (req, res) => {
  try {
    const { text, type } = req.body;
    if (!text) {
      return res.status(400).json({ error: "Text content is required" });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ error: "GEMINI_API_KEY environment variable is not set." });
    }

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        }
      }
    });

    const prompts: Record<string, string> = {
      bullet: "Summarize the following study material into clear, concise bullet points. Group related points under headings. Focus on key concepts, definitions, and important facts:\n\n",
      brief: "Write a brief summary (3-5 paragraphs) of the following study material. Cover the main ideas and key takeaways:\n\n",
      detailed: "Create detailed study notes from the following material. Include:\n- Key concepts and definitions\n- Important facts and figures\n- Relationships between ideas\n- Examples where helpful\nFormat with clear headings and subheadings:\n\n",
      qa: "Convert the following study material into a Q&A format. Create 8-12 important questions and answers that cover the key concepts. Format as:\n\n**Q: [question]**\nA: [answer]\n\nMaterial:\n\n",
      explain: "Explain the following study material in simple language that a 12-year-old student can understand. Use everyday examples and analogies. Avoid jargon:\n\n"
    };

    const promptPrefix = prompts[type] || prompts.bullet;
    const prompt = promptPrefix + text;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
    });

    const resultText = response.text;
    if (!resultText) {
      return res.status(500).json({ error: "No content was generated by Gemini." });
    }

    res.json({ text: resultText });
  } catch (error: any) {
    console.error("Error generating summary:", error);
    res.status(500).json({ error: error.message || "Failed to generate summary" });
  }
});

// Serve static assets from allowed directories
app.use("/css", express.static(path.join(process.cwd(), "css")));
app.use("/js", express.static(path.join(process.cwd(), "js")));
app.use("/pages", express.static(path.join(process.cwd(), "pages")));

// HTML page routing
app.get("/", (req, res) => {
  res.sendFile(path.join(process.cwd(), "index.html"));
});

const ROOT_FILES = ["index.html", "dashboard.html", "login.html", "setup.html", "test.txt"];
ROOT_FILES.forEach(file => {
  app.get(`/${file}`, (req, res) => {
    res.sendFile(path.join(process.cwd(), file));
  });
});

app.listen(PORT, "0.0.0.0", () => {
  console.log(`Server running on port ${PORT}`);
});
